### ISSUE TITLE
Unsupported class file major version 59 

### ISSUE THREAD

**Issue by samuel2629** [mobilekosmos/moralis-sdk-android#3]
Hello i found your project and i really need it and it seems amazing but this is what i got when trying to implement it : 
Unsupported class file major version 59 
Any idea ? 
Thx

**Comment by mobilekosmos** [comment]
You already found this?: https://stackoverflow.com/questions/68108265/java-lang-illegalargumentexception-unsupported-class-file-major-version-59

**Comment by samuel2629** [comment]
Yes tried that but doesnt work ! What your configurations plz

**Comment by samuel2629** [comment]
Don't create a repo for others if you don't want people to tell you that things are not ok in it.
